name: Windows Cloud RDP (with CMD via Tmate)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360   # حداکثر ۶ ساعت

    steps:
      - name: 1. Enable Remote Desktop & Firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0

      - name: 2. Create Admin Account
        run: |
          $Password = ConvertTo-SecureString "P@ssw0rd1qazXSW@#" -AsPlainText -Force
          New-LocalUser -Name "NvDAdmin" -Password $Password -PasswordNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "NvDAdmin" -ErrorAction SilentlyContinue
          net user runneradmin P@ssw0rd1qazXSW@#

      - name: 3. Get CMD access via Tmate (No Tailscale, No extra installs!)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # فقط خودتان (صاحب ریپو) دسترسی داشته باشید
